@startuml

package rape.brutal.gitstarship {

    class Universe {
        -int kills;
        -int spends;
        +startUniverse();
        +win();
        +lose();
    }

    class Storage {
        -HashMap<String, IStorageable> storage
        +void add(String itemName);
        +void remove(String itemName);
        -int capacity;
    }

    package trade {

        abstract class Trader {
            -int cash;
        }

        class BaseTrader extends Trader {
            +void trade();
        }

        class Mechanic extends Trader {
            +void repair(int cash, String itemName);
            +void upgrade(int cash, String itemName);
        }

    }

    package events {

        +abstract class Event {
            #Universe universe;
            #GitStarship gitStarship;

            +void start(GitStarship gitStarship);
        }

    }

    interface ILandable {
        +land(GitStarship gitStarship);
    }

    package locations {

        Location <.- ILandable

        +abstract class Location {
            #GitStarship gitStarship;
            #Trader trader;
            #Storage storage;
            #ArrayList<Starship> ships;
        }
    }

    interface IAttackable {
        +void setDamage(int damage);
        +int getHitPoints();
    }

    package ships {

        Starship <|-- GitStarship
        Starship <|-- PirateStarship

        abstract class Starship implements IAttackable {
            #Engine engine;
            #Hull hull;
            #Storage storage;

            +boolean putInStorage(IStoreable iStoreable);
            +IStoreable getFromStorage(String iStoreableName);
            +void trade(Trader trader);
            +void attack(IAttackable iAttackable);
        }

        class GitStarship {

        }

        class PirateStarship {

        }

    }

    interface IStorageable {
        +int getSize();
        +String getName();
    }

    package parts {

        abstract class ShipPart implements IStorageable {
            -int size;
        }

        class Hull extends ShipPart {
            -Gun gun[8];
            +addGun();
            +removeGun();
        }

        class Engine extends ShipPart {
            -int condition;
            -int power;
        }

    }

    package ammunition {

        Gun <|-- Turret
        Gun <|-- Railgun
        Turret o-- Magazine
        Magazine o- Ammo
        Ammo o- AmmoType

        +abstract class Gun {
            #int baseDamage;

            +void fire();
        }

        +class Turret {
            -Magazine loadedMagazine;

            +void reload(Magazine magazine);
        }

        +class Railgun {

        }

        +class Magazine {
            -int capacity;
            -Ammo[] ammo;

            +void removeAmmo();
        }

        +class Ammo {
            -int baseDamage;
            -AmmoType ammoType;

            +int getBaseDamage();
        }

        +enum AmmoType {

        }

    }

}

@enduml